### PR TITLE
Feature/tables component

### PR DESCRIPTION
**Pull request by elian-dev**
- Table component was created
- Full information in the clinical data / overview page

### CODE REVIEW

**Review by HackMort — CHANGES_REQUESTED** [review]
1. Table headings are on mobile needs to be adjust them. The text below Study 1, 2, etc needs to match the font-size, alignment and line spacing. 
image
2. Te table should go full-width on the right side of the screen, in other words it should not be touching the edge of the screen like in the Figma design.
image
3. All TDs should be vertical aligned.
image
4. Please check the styles for these lines of text. Also check the styles for the sup tags:
image
5. Wrong font styles:
image
6. This whole section needs to be revised on mobile, font-size, line-height, the table should go to the edge of the screen (to the right).
image
7.Similar to the comment above:
image
8. Please remove the References Component from the page and use the Layout Prop instead.

**Review by HackMort — CHANGES_REQUESTED** [review]
1. We need a bit of space in the first column, the "Description" word is touching the edge of the cell and it should not do that:
image
2. Some of these text should be in 2 lines on mobile & desktop:
image
3. On desktop please match the font size of the headings of the table:
image
4. Table is growing beyond the wrapper, please fix:
image
5. One more thing, what is happening here:
image

**Comment by elian-dev** [comment]
- Fix the spacing in tables 
- word breaks in some cellss
- correct font sizes
- content no grow beyond the wrapper
- the undifined classes

**Review by HackMort — CHANGES_REQUESTED** [review]
Minor tweaks:
1. On mobile can you decrease a little the width of the cell on this column? Alsoe the first Green Text/Heading should be in 2 lines on mobile.
image
2.Some of the green text should be in 1 line for mobile & desktop And there are a couple that have an "orphan" letter in other words, if it needs to go to the next line, it should be the whole word, not just one letter.
image
image
3. Increase the space between these 2 sections. 
image

**Comment by elian-dev** [comment]
Fixes done:
- Width of some columns
- Titles in one line
- Space between some sections

**Review by HackMort — APPROVED** [review]
You forgot to update the spacing between the 2 tables, but I added it. Good to go.

**Pull request merged**
